language: erlang

sudo: false

addons:
  apt:
    packages:
      - libreadline-dev
      - libncurses5-dev
      - libpcre3-dev
      - libssl-dev
      - build-essential

env:
  global:
    - CASSANDRA_VERSION=2.1.9
    - LUAROCKS_VERSION=2.2.2
    - OPENRESTY_VERSION=1.9.3.1 # integration only
    - LUA_DIR=$HOME/lua
    - LUAJIT_DIR=$HOME/luajit
    - LUAROCKS_DIR=$HOME/luarocks
    - OPENRESTY_DIR=$HOME/openresty # integration only
    - SMALL_LOAD=true
    - "HOSTS=127.0.0.1,127.0.0.2,127.0.0.3"
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit
    - perl: "5.18"
      OPENRESTY_TESTS: yes

before_install:
  - bash .ci/setup_cassandra.sh
  - bash .ci/setup_lua.sh
  - bash .ci/setup_openresty.sh
  - export PATH=$LUA_DIR/src:$PATH
  - export PATH=$LUAJIT_DIR/src:$PATH
  - export PATH=$LUAROCKS_DIR/bin:$PATH
  - export PATH=$OPENRESTY_DIR:$PATH
  - luarocks install ansicolors
  - make dev

script: .ci/run_tests.sh

cache:
  pip: true
  apt: true
  directories:
    - $LUAJIT_DIR
    - $OPENRESTY_DIR
    - $HOME/.ccm/repository/ # ccm cassandra version
    - $HOME/.local/lib # python packages for ccm
    - $HOME/.cpan

notifications:
  email: false
