language: erlang

env:
  global:
    - LUAROCKS=2.2.2
    - CASSANDRA_VERSION=2.1.9
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit

before_install:
  - bash .travis/setup_lua.sh
  - bash .travis/setup_cassandra.sh
  - sudo make dev

script:
  - "busted -v --coverage"
  - "make lint"

after_success: "luacov-coveralls -i cassandra"

notifications:
  email: false
