sudo: false
dist: trusty

language: java

jdk:
  - oraclejdk8

notifications:
  email: false

addons:
  apt:
    packages:
      - libreadline-dev
      - libncurses5-dev
      - libpcre3-dev
      - libssl-dev
      - build-essential

env:
  global:
    - LUAROCKS=2.4.1
    - OPENRESTY=1.15.8.1
    - DOWNLOAD_CACHE=$HOME/download-cache
    - INSTALL_CACHE=$HOME/install-cache
    - PERL_DIR=$HOME/perl5
  matrix:
    - LUA="lua 5.1"
    - LUA="lua 5.2"
    - LUA="luajit 2.0"
    - LUA="luajit 2.1"
    - OPENRESTY_TESTS=true
      CASSANDRA=3.9
    - OPENRESTY_TESTS=true
      CASSANDRA=2.2.8
    - OPENRESTY_TESTS=true
      CASSANDRA=2.1.16

before_install:
  - source .ci/setup_env.sh

install:
  - make install

script:
  - .ci/run_tests.sh

cache:
  cpan: true
  apt: true
  pip: true
  directories:
    - $PERL_DIR
    - $DOWNLOAD_CACHE
    - $INSTALL_CACHE
    - $HOME/.ccm/repository/
