language: erlang

sudo: false

env:
  global:
    - CASSANDRA_VERSION=2.1.9
    - LUAROCKS_VERSION=2.2.2
    - LUA_DIR=$HOME/lua
    - LUAJIT_DIR=$HOME/luajit
    - LUAROCKS_DIR=$HOME/luarocks
    - "HOSTS=127.0.0.1,127.0.0.2,127.0.0.3"
    - SMALL_LOAD=true
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit

before_install:
  - bash .ci/setup_cassandra.sh
  - bash .ci/setup_lua.sh
  - export PATH=$LUA_DIR/src:$PATH
  - export PATH=$LUAJIT_DIR/src:$PATH
  - export PATH=$LUAROCKS_DIR/bin:$PATH
  - luarocks install ansicolors
  - make dev

script:
  - busted -v --coverage -o .ci/busted_print.lua
  - make lint

after_success: luacov-coveralls -i cassandra

cache:
  directories:
    - $LUAJIT_DIR
    - $HOME/.ccm/repository/ # ccm cassandra version
    - $HOME/.local/lib # python packages for ccm

notifications:
  email: false
