local utils = require "cassandra.utils"

describe("utils", function()
  describe("is_array()", function()
    it("detects arrays", function()
      assert.True(utils.is_array {"a", "b", "c", "d"})
      assert.False(utils.is_array {["1"] = "a", ["2"] = "b", ["3"] = "c", ["4"] = "d"})
      assert.False(utils.is_array {"a", "b", "c", foo = "d"})
      assert.False(utils.is_array())
      assert.False(utils.is_array(false))
      assert.False(utils.is_array(true))
      assert.False(utils.is_array "")
    end)
  end)
end)
