local table_utils = require "cassandra.utils.table"

describe("table_utils", function()
  describe("is_array()", function()
    it("detects arrays", function()
      assert.True(table_utils.is_array {"a", "b", "c", "d"})
      assert.True(table_utils.is_array {["1"] = "a", ["2"] = "b", ["3"] = "c", ["4"] = "d"})
      assert.False(table_utils.is_array {"a", "b", "c", foo = "d"})
      assert.False(table_utils.is_array())
      assert.False(table_utils.is_array(false))
      assert.False(table_utils.is_array(true))
      assert.False(table_utils.is_array "")
    end)
  end)
end)
