local SUPPORTED_PROTOCOL_VERSION = {2, 3}
local DEFAULT_PROTOCOL_VERSION =  SUPPORTED_PROTOCOL_VERSION[#SUPPORTED_PROTOCOL_VERSION]

return {
  SUPPORTED_PROTOCOL_VERSION = SUPPORTED_PROTOCOL_VERSION,
  DEFAULT_PROTOCOL_VERSION = DEFAULT_PROTOCOL_VERSION,
  MIN_PROTOCOL_VERSION = SUPPORTED_PROTOCOL_VERSION[1],
  MAX_PROTOCOL_VERSION = DEFAULT_PROTOCOL_VERSION,
  CQL_VERSION = "3.0.0",
  DEFAULT_CQL_PORT = 9042
}
