local SUPPORTED_PROTOCOL_VERSIONS = {2, 3}
local DEFAULT_PROTOCOL_VERSION =  SUPPORTED_PROTOCOL_VERSIONS[#SUPPORTED_PROTOCOL_VERSIONS]

return {
  SUPPORTED_PROTOCOL_VERSIONS = SUPPORTED_PROTOCOL_VERSIONS,
  DEFAULT_PROTOCOL_VERSION = DEFAULT_PROTOCOL_VERSION,
  MIN_PROTOCOL_VERSION = SUPPORTED_PROTOCOL_VERSIONS[1],
  MAX_PROTOCOL_VERSION = DEFAULT_PROTOCOL_VERSION,
  CQL_VERSION = "3.0.0"
}
