local Client = require "cassandra.client"

describe("Client", function()
  it("should be instanciable", function()
    assert.has_no_errors(function()
      local client = Client({contact_points = {"127.0.0.1"}})
      assert.equal(false, client.connected)
    end)
  end)
  describe("#execute()", function()
    it("should return error if no host is available", function()
      local client = Client({contact_points = {"0.0.0.1", "0.0.0.2", "0.0.0.3"}})
      local err = client:execute()
      assert.truthy(err)
      assert.equal("NoHostAvailableError", err.type)
    end)
  end)
end)
